### ISSUE TITLE
重启开在 apfs_module_start:1609: load: com.apple.filesystems.apfs, v1412.101.1, apfs-1412.101.1, 2020/03/06

### ISSUE THREAD

**Issue by isfong** [sqlsec/B360M-DS3H-I5-9600KF-RX580-CLOVER#2]
安装成功后，从Windows下重启正常进入macos系统， 在macos下再重启就会出现禁行标志，-v查看， 卡在“apfs_module_start:1609: load: com.apple.filesystems.apfs, v1412.101.1, apfs-1412.101.1, 2020/03/06”， 又重启进入Windows再重启进入macos又可以，反正就是不能再macos 重启， 搜索说拔一下主板上的电池给主板断电， 然并卵，

系统: macOS Catalina 10.15.4
处理器：i7 8700
主板: 技嘉b360m ds3h
显卡: NVIDIA GeForce GT 730 2 GB（居然免驱？）
![51585454203_ pic](https://user-images.githubusercontent.com/25047541/77839980-b4d2fe80-71b4-11ea-9bd0-b20fcc06f9ac.jpg)

![61585454424_ pic](https://user-images.githubusercontent.com/25047541/77839993-e9df5100-71b4-11ea-914e-0cacf23bbcdc.jpg)

**Comment by isfong** [comment]
已经解决， 本来各种方法都试过了，已经放弃了重启卡主这个问题的修复， 没想到刷了最新的BIOS居然可以了，哈哈哈哈哈哈哈哈哈，给力， 完美。

**Comment by sqlsec** [comment]
我刚刚才看到这个issue （尴尬了） 解决了就好哈

**Comment by IPNUISTlegal** [comment]
@sqlsec 一样主板，但我是i5 8400。怎么在引导安装中，发现键盘和鼠标都点不了。请问大佬怎么解决

**Comment by isfong** [comment]
> @sqlsec 一样主板，但我是i5 8400。怎么在引导安装中，发现键盘和鼠标都点不了。请问大佬怎么解决
https://github.com/dortania/OpenCore-Install-Guide 自己配置定制OC EFI So easy
