### ISSUE TITLE
Stuck in the Apple logo not booting

### ISSUE THREAD

**Issue by hitman3r44** [sqlsec/B360M-DS3H-I5-9600KF-RX580-CLOVER#3]
HI i am using this harware:

B360M-DS3H
I5-9600KF

Tried to install Macos 15.5 Catalina with this CLOVER file
But i can't boot its stuck in apple logo

Can you tell me any solution

**Comment by sqlsec** [comment]
I haven't considered adapting Macos 15.5 Catalina system，You can try to upgrade clover, maybe it will succeed

**Comment by hitman3r44** [comment]
Ok thanks for the reply

**Comment by sqlsec** [comment]
You may not believe it. noe this project supports Catalina 10.15.7 and Big Sur 11.4 @hitman3r44

**Comment by hitman3r44** [comment]
Wow that's great to know that, unfortunately i sold the system
