### ISSUE TITLE
B460M-KYLIN-I5-10400

### ISSUE THREAD

**Issue by lingwebber** [sqlsec/B360M-DS3H-I5-9600KF-RX580-CLOVER#4]
Hi
I am refering your clover to install highsierra on my device.
But it stuck at end random seed.

I am using ASUS B460M-Kylin with i5-10400

Have you got any idea?

Thanks

**Comment by r0ot-to0r** [comment]
请教大佬有没有2021的黑苹果台式机配置推荐 预算6-8k。（不算外设）

**Comment by sqlsec** [comment]
@r0ot-to0r  可以去黑苹果小兵的那个长期维护机型清单里面 或者去远景论坛搜索看看，还有 B 站也会有一些不错的黑苹果方案装机视频。
